Fix AttributeError: 'int' object has no attribute 'decode'
When using pyosmium-get-changes, which use urllib to download changes from
remote server it was failing due to the fact, that call to
urllib.response.readline() was returning bytes, which were in the for loop
interpeted one by one.